language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^4.2'
    - php: 7.3
      env: SYMFONY_VERSION='^3.4'
    - php: 7.3
      env: SYMFONY_VERSION='^4.2'
  fast_finish: true

before_script:
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - composer config extra.symfony.require "$SYMFONY_VERSION"
  - composer update

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit
