language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION='~3.3.0'
    - php: 5.6
      env: SYMFONY_VERSION='~3.3.0'
    - php: 7.0
      env: SYMFONY_VERSION='~3.3.0'
    - php: 7.0
      env: SYMFONY_VERSION='~3.4.0'
    - php: 7.1
      env: SYMFONY_VERSION='~3.3.0'
    - php: 7.1
      env: SYMFONY_VERSION='~3.4.0'
    - php: 7.2
      env: SYMFONY_VERSION='~3.4.0'
    - php: 7.2
      env: SYMFONY_VERSION='~4.0.0'

  fast_finish: true

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}" "symfony/security-bundle:${SYMFONY_VERSION}" "symfony/validator:${SYMFONY_VERSION}" "symfony/expression-language:${SYMFONY_VERSION}" "symfony/serializer:${SYMFONY_VERSION}"; fi;
  - composer update

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit
