parameters:
    mcfedr_aws_push.platforms: []
    mcfedr_aws_push.aws.credentials: ~
    mcfedr_aws_push.aws.region: ''
    mcfedr_aws_push.debug: false
    mcfedr_aws_push.topic_arn: ''

services:
    Mcfedr\AwsPushBundle\Service\Devices:
        public: true
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"

    Mcfedr\AwsPushBundle\Service\Messages:
        public: true
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "%mcfedr_aws_push.debug%"
          - "@?logger"

    Mcfedr\AwsPushBundle\Service\Topics:
        public: true
        arguments:
            - "@mcfedr_aws_push.sns_client"
            - '@Mcfedr\AwsPushBundle\Service\Messages'
            - "%mcfedr_aws_push.debug%"
            - "@?logger"

    Mcfedr\AwsPushBundle\Command\SubscribeTopicsCommand:
        arguments:
          - "%mcfedr_aws_push.topic_arn%"
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@?logger"
        tags:
          -  { name: console.command }

    Mcfedr\AwsPushBundle\Command\EnableAllCommand:
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@?logger"
        tags:
          -  { name: console.command }

    Mcfedr\AwsPushBundle\Command\RemoveDisabledCommand:
        arguments:
          - "@mcfedr_aws_push.sns_client"
          - "%mcfedr_aws_push.platforms%"
          - "@?logger"
        tags:
          -  { name: console.command }

    mcfedr_aws_push.sns_client:
        public: true
        class: Aws\Sns\SnsClient
        arguments:
          -
            version: "2010-03-31"
            region: "%mcfedr_aws_push.aws.region%"
            credentials: "%mcfedr_aws_push.aws.credentials%"

    Mcfedr\AwsPushBundle\Controller\:
        public: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

# public aliases for back compat
    mcfedr_aws_push.topics:
        alias: Mcfedr\AwsPushBundle\Service\Topics
        public: true

    mcfedr_aws_push.devices:
        alias: Mcfedr\AwsPushBundle\Service\Devices
        public: true

    mcfedr_aws_push.messages:
        alias: Mcfedr\AwsPushBundle\Service\Messages
        public: true
